name: "Update SRI hash"
on:
  workflow_dispatch:

jobs:
  update_sri_hash:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Cache install Nix packages
        uses: mtoohey31/cache-flake-attrs@v2
        with:
          key: ${{ runner.os }}-nix-${{ hashFiles('./flake.nix') }}
          flake_paths: ".#regenSRI"
      - name: re-generate SRI
        run: "nix --extra-experimental-features nix-command --extra-experimental-features flakes run .#regenSRI"
      - name: Commit & Push updated SRI
        uses: actions-js/push@v1.4
        with:
          message: "chore: Update SRI hashes"
          branch: ${{github.ref_name}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
